import { Geist, Geist_Mono, Delius, Delius_Swash_Caps } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const delius = Delius({
  weight: ['400'],
  variable: "--font-delius",
  subsets: ["latin"],
});

const deliusSwashCaps = Delius_Swash_Caps({
  weight: ['400'],
  variable: "--font-delius-swash-caps",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${delius.variable} ${deliusSwashCaps.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${delius.variable} ${deliusSwashCaps.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
